name: artip
channels:
   - pkgw-forge
   - conda-forge
 dependencies:
 - python=2.7
 - casa-data
 - casa-python=4.7.2
- pip
- pip:
  - pybuilder
  - ipython
  - coloredlogs
  - pyyaml
  - scipy
  - lsprofcalltree
  - conditional
  - mock
  - watchdog
  - sh
  - click